### ISSUE TITLE
Client crashes due to missing Plotly dependency

### ISSUE THREAD

**Issue by wk9874** [simvue-io/client#157]
Since the move to Poetry, Plotly is listed as an optional extra. However after pip installing the base simvue with no extras, and then trying to run a script which does not use plotting, I still get the following error:

```
Traceback (most recent call last):
  File "/home/dev/moose-training-workshop/tutorial/step_6/moose_monitoring.py", line 1, in <module>
    import simvue
  File "/home/dev/.pyenv/versions/3.10.13/lib/python3.10/site-packages/simvue/__init__.py", line 1, in <module>
    from simvue.run import Run
  File "/home/dev/.pyenv/versions/3.10.13/lib/python3.10/site-packages/simvue/run.py", line 18, in <module>
    from .serialization import Serializer
  File "/home/dev/.pyenv/versions/3.10.13/lib/python3.10/site-packages/simvue/serialization.py", line 3, in <module>
    import plotly
ModuleNotFoundError: No module named 'plotly'
```

Looks like Plotly is used inside the serializer, which is imported by run, so will always be required in the current version

**Comment by alahiff** [comment]
Resolved by https://github.com/simvue-io/client/pull/153 which has now been merged.
