### ISSUE TITLE
`simvue_sender` no longer works due to migration to poetry

### ISSUE THREAD

**Issue by alahiff** [simvue-io/client#170]

**Comment by alahiff** [comment]
After running `pip install simvue==1.0.0.dev3`:
```
% simvue_sender 
/opt/homebrew/bin/simvue_sender:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('simvue==0.15.0', 'simvue_sender')
Traceback (most recent call last):
  File "/opt/homebrew/bin/simvue_sender", line 4, in <module>
    __import__('pkg_resources').run_script('simvue==0.15.0', 'simvue_sender')
  File "/opt/homebrew/lib/python3.11/site-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/homebrew/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1548, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/simvue_sender' not found in metadata at '/opt/homebrew/lib/python3.11/site-packages/simvue-0.15.0.dist-info'
```

**Comment by alahiff** [comment]
Fixed by https://github.com/simvue-io/client/commit/5003b1ea9feb367af63333794d5eafc5be6f7720
