### ISSUE TITLE
Error message is confusing upon trying to create a duplicate run

### ISSUE THREAD

**Issue by alahiff** [simvue-io/client#61]
The 409 is no longer recognised correctly.
```
Traceback (most recent call last):
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/simvue/api.py", line 31, in post
    response.raise_for_status()
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://app.simvue.io/api/runs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/simvue/remote.py", line 39, in create_run
    response = post(f"{self._url}/api/runs", self._headers, data)
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x106b1d780 state=finished raised HTTPError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewlahiff/Work/Observability/c50/test1.py", line 6, in <module>
    run.init(name='wed-2st-march', folder='/tests/deletetest1')
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/simvue/run.py", line 281, in init
    name = self._simvue.create_run(data)
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/simvue/remote.py", line 41, in create_run
    self._error(f"Exception creating run: {str(err)}")
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/simvue/remote.py", line 30, in _error
    raise RuntimeError(message)
RuntimeError: Exception creating run: RetryError[<Future at 0x106b1d780 state=finished raised HTTPError>]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/andrewlahiff/Work/Observability/c50/test1.py", line 4, in <module>
    with Run() as run:
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/simvue/run.py", line 168, in __exit__
    self.log_event(f"{type.__name__}: {value}")
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/simvue/run.py", line 417, in log_event
    self._error('Run is not active')
  File "/Users/andrewlahiff/Work/Observability/c50/venv/lib/python3.10/site-packages/simvue/run.py", line 226, in _error
    raise RuntimeError(message)
RuntimeError: Run is not active
```

**Comment by alahiff** [comment]
Fixed in https://github.com/simvue-io/client/tree/fix_409 (including the `Run is not active` error)

**Comment by alahiff** [comment]
https://github.com/simvue-io/client/pull/66 merged
